#include <iostream>
#include <array>
#include <utility>

enum class compound {
	pomeranians,
	goldfish,
	children,
	samoyeds,
	akitas,
	vizslas,
	cars,
	perfumes,
	cats,
	trees,
};

using data = std::pair<compound, int>;
using aunt = std::array<data, 3>;


int main() {
	std::array<aunt, 500> aunts{
		aunt{data{compound::cars, 9}, {compound::akitas, 3}, {compound::goldfish, 0}},
		aunt{data{compound::akitas, 9}, {compound::children, 3}, {compound::samoyeds, 9}},
		aunt{data{compound::trees, 6}, {compound::cars, 6}, {compound::children, 4}},
		aunt{data{compound::trees, 4}, {compound::vizslas, 4}, {compound::goldfish, 9}},
		aunt{data{compound::akitas, 9}, {compound::vizslas, 7}, {compound::cars, 5}},
		aunt{data{compound::vizslas, 6}, {compound::goldfish, 6}, {compound::akitas, 3}},
		aunt{data{compound::pomeranians, 5}, {compound::samoyeds, 0}, {compound::perfumes, 10}},
		aunt{data{compound::cars, 10}, {compound::pomeranians, 7}, {compound::goldfish, 8}},
		aunt{data{compound::trees, 2}, {compound::vizslas, 7}, {compound::samoyeds, 6}},
		aunt{data{compound::perfumes, 5}, {compound::pomeranians, 4}, {compound::children, 9}},
		aunt{data{compound::vizslas, 5}, {compound::perfumes, 8}, {compound::cars, 10}},
		aunt{data{compound::children, 10}, {compound::cars, 6}, {compound::perfumes, 5}},
		aunt{data{compound::cats, 4}, {compound::samoyeds, 7}, {compound::pomeranians, 8}},
		aunt{data{compound::perfumes, 6}, {compound::goldfish, 10}, {compound::children, 7}},
		aunt{data{compound::perfumes, 4}, {compound::pomeranians, 3}, {compound::cars, 6}},
		aunt{data{compound::perfumes, 7}, {compound::cars, 9}, {compound::pomeranians, 6}},
		aunt{data{compound::goldfish, 3}, {compound::cars, 6}, {compound::vizslas, 7}},
		aunt{data{compound::perfumes, 6}, {compound::cars, 7}, {compound::goldfish, 3}},
		aunt{data{compound::trees, 0}, {compound::akitas, 3}, {compound::pomeranians, 8}},
		aunt{data{compound::goldfish, 6}, {compound::trees, 2}, {compound::akitas, 6}},
		aunt{data{compound::pomeranians, 9}, {compound::akitas, 9}, {compound::samoyeds, 9}},
		aunt{data{compound::vizslas, 2}, {compound::cars, 9}, {compound::perfumes, 5}},
		aunt{data{compound::goldfish, 10}, {compound::samoyeds, 8}, {compound::children, 9}},
		aunt{data{compound::akitas, 4}, {compound::goldfish, 1}, {compound::vizslas, 5}},
		aunt{data{compound::goldfish, 10}, {compound::trees, 8}, {compound::perfumes, 6}},
		aunt{data{compound::vizslas, 5}, {compound::akitas, 8}, {compound::trees, 1}},
		aunt{data{compound::trees, 3}, {compound::cars, 6}, {compound::perfumes, 2}},
		aunt{data{compound::goldfish, 8}, {compound::trees, 7}, {compound::akitas, 10}},
		aunt{data{compound::children, 5}, {compound::trees, 1}, {compound::goldfish, 10}},
		aunt{data{compound::vizslas, 3}, {compound::perfumes, 8}, {compound::akitas, 3}},
		aunt{data{compound::cars, 6}, {compound::children, 10}, {compound::perfumes, 7}},
		aunt{data{compound::cars, 10}, {compound::perfumes, 3}, {compound::goldfish, 10}},
		aunt{data{compound::perfumes, 9}, {compound::vizslas, 3}, {compound::akitas, 4}},
		aunt{data{compound::perfumes, 10}, {compound::vizslas, 7}, {compound::children, 8}},
		aunt{data{compound::cars, 5}, {compound::perfumes, 5}, {compound::vizslas, 9}},
		aunt{data{compound::trees, 9}, {compound::cars, 9}, {compound::akitas, 7}},
		aunt{data{compound::samoyeds, 9}, {compound::perfumes, 2}, {compound::cars, 10}},
		aunt{data{compound::akitas, 7}, {compound::cars, 5}, {compound::trees, 5}},
		aunt{data{compound::goldfish, 8}, {compound::trees, 9}, {compound::cars, 10}},
		aunt{data{compound::trees, 0}, {compound::cats, 1}, {compound::pomeranians, 1}},
		aunt{data{compound::pomeranians, 6}, {compound::perfumes, 9}, {compound::samoyeds, 1}},
		aunt{data{compound::vizslas, 6}, {compound::akitas, 3}, {compound::pomeranians, 1}},
		aunt{data{compound::vizslas, 2}, {compound::perfumes, 3}, {compound::pomeranians, 6}},
		aunt{data{compound::akitas, 5}, {compound::pomeranians, 0}, {compound::vizslas, 10}},
		aunt{data{compound::vizslas, 4}, {compound::goldfish, 1}, {compound::cars, 5}},
		aunt{data{compound::cars, 4}, {compound::vizslas, 8}, {compound::cats, 0}},
		aunt{data{compound::cats, 5}, {compound::children, 8}, {compound::pomeranians, 2}},
		aunt{data{compound::vizslas, 3}, {compound::perfumes, 6}, {compound::cats, 0}},
		aunt{data{compound::akitas, 7}, {compound::perfumes, 0}, {compound::trees, 7}},
		aunt{data{compound::trees, 4}, {compound::akitas, 10}, {compound::vizslas, 2}},
		aunt{data{compound::goldfish, 10}, {compound::cars, 9}, {compound::trees, 4}},
		aunt{data{compound::cars, 5}, {compound::children, 9}, {compound::perfumes, 0}},
		aunt{data{compound::vizslas, 5}, {compound::cars, 3}, {compound::cats, 8}},
		aunt{data{compound::cars, 5}, {compound::akitas, 1}, {compound::goldfish, 10}},
		aunt{data{compound::akitas, 10}, {compound::vizslas, 2}, {compound::cars, 6}},
		aunt{data{compound::cats, 6}, {compound::trees, 0}, {compound::cars, 4}},
		aunt{data{compound::vizslas, 1}, {compound::akitas, 1}, {compound::samoyeds, 7}},
		aunt{data{compound::samoyeds, 6}, {compound::vizslas, 1}, {compound::akitas, 7}},
		aunt{data{compound::akitas, 9}, {compound::cars, 8}, {compound::vizslas, 1}},
		aunt{data{compound::cars, 6}, {compound::vizslas, 7}, {compound::goldfish, 0}},
		aunt{data{compound::pomeranians, 5}, {compound::akitas, 6}, {compound::vizslas, 2}},
		aunt{data{compound::samoyeds, 2}, {compound::cats, 8}, {compound::goldfish, 7}},
		aunt{data{compound::vizslas, 10}, {compound::goldfish, 7}, {compound::samoyeds, 9}},
		aunt{data{compound::perfumes, 2}, {compound::trees, 1}, {compound::akitas, 6}},
		aunt{data{compound::cars, 8}, {compound::perfumes, 10}, {compound::vizslas, 9}},
		aunt{data{compound::akitas, 8}, {compound::vizslas, 8}, {compound::perfumes, 8}},
		aunt{data{compound::goldfish, 7}, {compound::cars, 9}, {compound::samoyeds, 9}},
		aunt{data{compound::perfumes, 2}, {compound::children, 7}, {compound::akitas, 1}},
		aunt{data{compound::perfumes, 7}, {compound::vizslas, 9}, {compound::akitas, 1}},
		aunt{data{compound::samoyeds, 3}, {compound::vizslas, 1}, {compound::trees, 1}},
		aunt{data{compound::vizslas, 8}, {compound::goldfish, 7}, {compound::trees, 9}},
		aunt{data{compound::goldfish, 8}, {compound::cars, 6}, {compound::trees, 9}},
		aunt{data{compound::perfumes, 5}, {compound::cars, 10}, {compound::samoyeds, 7}},
		aunt{data{compound::pomeranians, 4}, {compound::perfumes, 3}, {compound::cars, 5}},
		aunt{data{compound::samoyeds, 1}, {compound::perfumes, 1}, {compound::pomeranians, 1}},
		aunt{data{compound::goldfish, 4}, {compound::cats, 6}, {compound::akitas, 7}},
		aunt{data{compound::perfumes, 5}, {compound::akitas, 4}, {compound::vizslas, 8}},
		aunt{data{compound::perfumes, 4}, {compound::cats, 3}, {compound::children, 4}},
		aunt{data{compound::vizslas, 5}, {compound::pomeranians, 9}, {compound::samoyeds, 7}},
		aunt{data{compound::cars, 3}, {compound::samoyeds, 5}, {compound::pomeranians, 7}},
		aunt{data{compound::vizslas, 2}, {compound::samoyeds, 4}, {compound::perfumes, 2}},
		aunt{data{compound::trees, 1}, {compound::akitas, 10}, {compound::vizslas, 9}},
		aunt{data{compound::vizslas, 0}, {compound::akitas, 2}, {compound::samoyeds, 5}},
		aunt{data{compound::perfumes, 5}, {compound::vizslas, 7}, {compound::children, 8}},
		aunt{data{compound::cats, 3}, {compound::children, 2}, {compound::trees, 0}},
		aunt{data{compound::cars, 3}, {compound::perfumes, 2}, {compound::goldfish, 2}},
		aunt{data{compound::trees, 1}, {compound::akitas, 7}, {compound::vizslas, 0}},
		aunt{data{compound::trees, 1}, {compound::akitas, 2}, {compound::samoyeds, 1}},
		aunt{data{compound::cars, 4}, {compound::vizslas, 8}, {compound::akitas, 1}},
		aunt{data{compound::perfumes, 5}, {compound::cats, 3}, {compound::vizslas, 0}},
		aunt{data{compound::samoyeds, 7}, {compound::cats, 6}, {compound::goldfish, 8}},
		aunt{data{compound::samoyeds, 10}, {compound::cats, 0}, {compound::cars, 7}},
		aunt{data{compound::cars, 6}, {compound::akitas, 7}, {compound::samoyeds, 2}},
		aunt{data{compound::perfumes, 0}, {compound::goldfish, 6}, {compound::trees, 9}},
		aunt{data{compound::cars, 6}, {compound::pomeranians, 2}, {compound::samoyeds, 8}},
		aunt{data{compound::cars, 2}, {compound::trees, 9}, {compound::samoyeds, 4}},
		aunt{data{compound::goldfish, 5}, {compound::trees, 1}, {compound::children, 0}},
		aunt{data{compound::akitas, 9}, {compound::goldfish, 7}, {compound::children, 6}},
		aunt{data{compound::goldfish, 9}, {compound::akitas, 0}, {compound::pomeranians, 0}},
		aunt{data{compound::samoyeds, 6}, {compound::children, 8}, {compound::vizslas, 5}},
		aunt{data{compound::vizslas, 6}, {compound::cars, 5}, {compound::goldfish, 4}},
		aunt{data{compound::vizslas, 6}, {compound::akitas, 2}, {compound::perfumes, 6}},
		aunt{data{compound::samoyeds, 3}, {compound::akitas, 7}, {compound::children, 4}},
		aunt{data{compound::cars, 3}, {compound::perfumes, 10}, {compound::cats, 6}},
		aunt{data{compound::vizslas, 9}, {compound::pomeranians, 0}, {compound::cars, 1}},
		aunt{data{compound::cats, 6}, {compound::samoyeds, 8}, {compound::pomeranians, 5}},
		aunt{data{compound::cars, 7}, {compound::trees, 4}, {compound::akitas, 10}},
		aunt{data{compound::perfumes, 3}, {compound::vizslas, 1}, {compound::goldfish, 9}},
		aunt{data{compound::trees, 6}, {compound::cars, 8}, {compound::goldfish, 5}},
		aunt{data{compound::pomeranians, 2}, {compound::children, 1}, {compound::vizslas, 7}},
		aunt{data{compound::akitas, 0}, {compound::vizslas, 8}, {compound::cars, 0}},
		aunt{data{compound::goldfish, 3}, {compound::vizslas, 6}, {compound::akitas, 2}},
		aunt{data{compound::akitas, 10}, {compound::pomeranians, 7}, {compound::perfumes, 7}},
		aunt{data{compound::cars, 10}, {compound::cats, 2}, {compound::vizslas, 8}},
		aunt{data{compound::akitas, 8}, {compound::trees, 1}, {compound::vizslas, 2}},
		aunt{data{compound::vizslas, 2}, {compound::akitas, 7}, {compound::perfumes, 1}},
		aunt{data{compound::goldfish, 0}, {compound::vizslas, 10}, {compound::trees, 9}},
		aunt{data{compound::trees, 3}, {compound::cars, 0}, {compound::goldfish, 0}},
		aunt{data{compound::perfumes, 7}, {compound::goldfish, 5}, {compound::trees, 9}},
		aunt{data{compound::children, 9}, {compound::vizslas, 3}, {compound::trees, 5}},
		aunt{data{compound::vizslas, 1}, {compound::goldfish, 7}, {compound::akitas, 10}},
		aunt{data{compound::perfumes, 1}, {compound::cars, 6}, {compound::trees, 1}},
		aunt{data{compound::akitas, 2}, {compound::vizslas, 0}, {compound::goldfish, 7}},
		aunt{data{compound::vizslas, 10}, {compound::pomeranians, 7}, {compound::akitas, 0}},
		aunt{data{compound::perfumes, 4}, {compound::cats, 5}, {compound::vizslas, 2}},
		aunt{data{compound::cars, 6}, {compound::samoyeds, 8}, {compound::akitas, 3}},
		aunt{data{compound::trees, 9}, {compound::goldfish, 7}, {compound::akitas, 9}},
		aunt{data{compound::cars, 8}, {compound::trees, 0}, {compound::perfumes, 2}},
		aunt{data{compound::pomeranians, 7}, {compound::vizslas, 2}, {compound::perfumes, 6}},
		aunt{data{compound::vizslas, 9}, {compound::pomeranians, 3}, {compound::trees, 6}},
		aunt{data{compound::vizslas, 7}, {compound::cars, 9}, {compound::perfumes, 1}},
		aunt{data{compound::akitas, 2}, {compound::pomeranians, 9}, {compound::vizslas, 7}},
		aunt{data{compound::trees, 9}, {compound::pomeranians, 10}, {compound::samoyeds, 0}},
		aunt{data{compound::children, 4}, {compound::akitas, 10}, {compound::perfumes, 4}},
		aunt{data{compound::vizslas, 1}, {compound::cats, 1}, {compound::trees, 8}},
		aunt{data{compound::samoyeds, 7}, {compound::cars, 8}, {compound::goldfish, 5}},
		aunt{data{compound::perfumes, 0}, {compound::children, 1}, {compound::pomeranians, 10}},
		aunt{data{compound::vizslas, 4}, {compound::perfumes, 5}, {compound::cars, 5}},
		aunt{data{compound::trees, 2}, {compound::perfumes, 8}, {compound::goldfish, 0}},
		aunt{data{compound::cars, 10}, {compound::akitas, 5}, {compound::goldfish, 7}},
		aunt{data{compound::children, 4}, {compound::trees, 3}, {compound::goldfish, 8}},
		aunt{data{compound::cars, 8}, {compound::perfumes, 6}, {compound::trees, 7}},
		aunt{data{compound::akitas, 6}, {compound::goldfish, 0}, {compound::trees, 10}},
		aunt{data{compound::akitas, 7}, {compound::pomeranians, 10}, {compound::perfumes, 10}},
		aunt{data{compound::trees, 10}, {compound::vizslas, 3}, {compound::goldfish, 4}},
		aunt{data{compound::samoyeds, 4}, {compound::akitas, 3}, {compound::perfumes, 6}},
		aunt{data{compound::akitas, 8}, {compound::perfumes, 2}, {compound::pomeranians, 10}},
		aunt{data{compound::cars, 2}, {compound::perfumes, 0}, {compound::goldfish, 8}},
		aunt{data{compound::goldfish, 6}, {compound::akitas, 7}, {compound::perfumes, 6}},
		aunt{data{compound::cars, 2}, {compound::pomeranians, 5}, {compound::perfumes, 4}},
		aunt{data{compound::goldfish, 1}, {compound::cars, 5}, {compound::trees, 0}},
		aunt{data{compound::pomeranians, 4}, {compound::cars, 7}, {compound::children, 1}},
		aunt{data{compound::goldfish, 8}, {compound::cars, 1}, {compound::children, 10}},
		aunt{data{compound::cars, 6}, {compound::perfumes, 8}, {compound::trees, 1}},
		aunt{data{compound::akitas, 4}, {compound::perfumes, 6}, {compound::pomeranians, 2}},
		aunt{data{compound::pomeranians, 5}, {compound::cars, 4}, {compound::akitas, 1}},
		aunt{data{compound::cats, 5}, {compound::cars, 9}, {compound::goldfish, 8}},
		aunt{data{compound::vizslas, 5}, {compound::samoyeds, 1}, {compound::children, 7}},
		aunt{data{compound::vizslas, 1}, {compound::perfumes, 3}, {compound::akitas, 1}},
		aunt{data{compound::goldfish, 10}, {compound::pomeranians, 9}, {compound::perfumes, 5}},
		aunt{data{compound::samoyeds, 3}, {compound::trees, 7}, {compound::cars, 2}},
		aunt{data{compound::cars, 2}, {compound::pomeranians, 1}, {compound::vizslas, 6}},
		aunt{data{compound::vizslas, 3}, {compound::perfumes, 5}, {compound::akitas, 6}},
		aunt{data{compound::vizslas, 1}, {compound::trees, 0}, {compound::akitas, 5}},
		aunt{data{compound::vizslas, 5}, {compound::cars, 6}, {compound::pomeranians, 8}},
		aunt{data{compound::cars, 10}, {compound::perfumes, 2}, {compound::trees, 9}},
		aunt{data{compound::cars, 10}, {compound::pomeranians, 6}, {compound::perfumes, 4}},
		aunt{data{compound::akitas, 7}, {compound::trees, 10}, {compound::goldfish, 7}},
		aunt{data{compound::akitas, 1}, {compound::perfumes, 10}, {compound::cars, 10}},
		aunt{data{compound::akitas, 5}, {compound::samoyeds, 8}, {compound::vizslas, 6}},
		aunt{data{compound::children, 3}, {compound::akitas, 2}, {compound::vizslas, 3}},
		aunt{data{compound::goldfish, 5}, {compound::vizslas, 5}, {compound::perfumes, 9}},
		aunt{data{compound::perfumes, 5}, {compound::goldfish, 10}, {compound::trees, 5}},
		aunt{data{compound::akitas, 5}, {compound::vizslas, 2}, {compound::children, 7}},
		aunt{data{compound::perfumes, 5}, {compound::cars, 7}, {compound::samoyeds, 2}},
		aunt{data{compound::cars, 8}, {compound::vizslas, 10}, {compound::akitas, 7}},
		aunt{data{compound::perfumes, 7}, {compound::children, 8}, {compound::goldfish, 7}},
		aunt{data{compound::cars, 1}, {compound::pomeranians, 9}, {compound::samoyeds, 0}},
		aunt{data{compound::perfumes, 6}, {compound::cars, 2}, {compound::trees, 6}},
		aunt{data{compound::trees, 3}, {compound::vizslas, 7}, {compound::children, 3}},
		aunt{data{compound::vizslas, 8}, {compound::samoyeds, 2}, {compound::trees, 9}},
		aunt{data{compound::perfumes, 3}, {compound::cats, 1}, {compound::children, 5}},
		aunt{data{compound::akitas, 9}, {compound::cats, 6}, {compound::children, 3}},
		aunt{data{compound::pomeranians, 9}, {compound::cars, 6}, {compound::perfumes, 8}},
		aunt{data{compound::vizslas, 9}, {compound::trees, 0}, {compound::akitas, 9}},
		aunt{data{compound::perfumes, 6}, {compound::cars, 5}, {compound::goldfish, 5}},
		aunt{data{compound::perfumes, 4}, {compound::cats, 7}, {compound::vizslas, 2}},
		aunt{data{compound::akitas, 7}, {compound::cars, 4}, {compound::children, 10}},
		aunt{data{compound::akitas, 0}, {compound::goldfish, 7}, {compound::vizslas, 5}},
		aunt{data{compound::akitas, 5}, {compound::cars, 5}, {compound::cats, 6}},
		aunt{data{compound::cars, 6}, {compound::children, 0}, {compound::perfumes, 3}},
		aunt{data{compound::cats, 2}, {compound::perfumes, 10}, {compound::goldfish, 7}},
		aunt{data{compound::trees, 1}, {compound::perfumes, 0}, {compound::cars, 8}},
		aunt{data{compound::perfumes, 9}, {compound::children, 4}, {compound::cats, 6}},
		aunt{data{compound::akitas, 7}, {compound::trees, 3}, {compound::goldfish, 6}},
		aunt{data{compound::goldfish, 8}, {compound::cars, 8}, {compound::samoyeds, 0}},
		aunt{data{compound::cats, 0}, {compound::akitas, 10}, {compound::vizslas, 0}},
		aunt{data{compound::goldfish, 1}, {compound::perfumes, 3}, {compound::cars, 8}},
		aunt{data{compound::akitas, 10}, {compound::vizslas, 5}, {compound::samoyeds, 6}},
		aunt{data{compound::pomeranians, 9}, {compound::goldfish, 9}, {compound::samoyeds, 7}},
		aunt{data{compound::samoyeds, 0}, {compound::goldfish, 7}, {compound::akitas, 6}},
		aunt{data{compound::vizslas, 0}, {compound::goldfish, 2}, {compound::akitas, 1}},
		aunt{data{compound::goldfish, 3}, {compound::children, 0}, {compound::vizslas, 8}},
		aunt{data{compound::cars, 8}, {compound::trees, 2}, {compound::perfumes, 2}},
		aunt{data{compound::cars, 4}, {compound::perfumes, 5}, {compound::goldfish, 8}},
		aunt{data{compound::vizslas, 3}, {compound::trees, 2}, {compound::akitas, 1}},
		aunt{data{compound::cars, 7}, {compound::goldfish, 5}, {compound::trees, 1}},
		aunt{data{compound::goldfish, 1}, {compound::cars, 6}, {compound::vizslas, 8}},
		aunt{data{compound::cats, 4}, {compound::trees, 1}, {compound::children, 0}},
		aunt{data{compound::cats, 10}, {compound::children, 0}, {compound::perfumes, 0}},
		aunt{data{compound::cars, 4}, {compound::pomeranians, 7}, {compound::samoyeds, 5}},
		aunt{data{compound::cars, 2}, {compound::pomeranians, 10}, {compound::trees, 1}},
		aunt{data{compound::trees, 10}, {compound::cats, 5}, {compound::cars, 10}},
		aunt{data{compound::perfumes, 5}, {compound::trees, 1}, {compound::vizslas, 1}},
		aunt{data{compound::akitas, 10}, {compound::vizslas, 8}, {compound::samoyeds, 8}},
		aunt{data{compound::vizslas, 2}, {compound::cats, 5}, {compound::pomeranians, 3}},
		aunt{data{compound::akitas, 10}, {compound::perfumes, 0}, {compound::cats, 10}},
		aunt{data{compound::trees, 8}, {compound::cats, 5}, {compound::vizslas, 2}},
		aunt{data{compound::goldfish, 10}, {compound::perfumes, 8}, {compound::children, 2}},
		aunt{data{compound::samoyeds, 9}, {compound::trees, 8}, {compound::vizslas, 7}},
		aunt{data{compound::children, 7}, {compound::trees, 6}, {compound::cars, 6}},
		aunt{data{compound::cats, 4}, {compound::akitas, 5}, {compound::pomeranians, 0}},
		aunt{data{compound::trees, 8}, {compound::goldfish, 2}, {compound::perfumes, 8}},
		aunt{data{compound::pomeranians, 9}, {compound::cars, 8}, {compound::akitas, 5}},
		aunt{data{compound::akitas, 10}, {compound::vizslas, 0}, {compound::trees, 2}},
		aunt{data{compound::akitas, 8}, {compound::cats, 6}, {compound::cars, 7}},
		aunt{data{compound::trees, 1}, {compound::akitas, 3}, {compound::goldfish, 4}},
		aunt{data{compound::pomeranians, 6}, {compound::cats, 3}, {compound::goldfish, 3}},
		aunt{data{compound::trees, 10}, {compound::perfumes, 3}, {compound::vizslas, 7}},
		aunt{data{compound::perfumes, 8}, {compound::cars, 7}, {compound::akitas, 0}},
		aunt{data{compound::perfumes, 10}, {compound::goldfish, 4}, {compound::cars, 6}},
		aunt{data{compound::goldfish, 7}, {compound::trees, 3}, {compound::cats, 2}},
		aunt{data{compound::perfumes, 6}, {compound::trees, 4}, {compound::akitas, 4}},
		aunt{data{compound::goldfish, 9}, {compound::cats, 4}, {compound::cars, 7}},
		aunt{data{compound::pomeranians, 6}, {compound::vizslas, 0}, {compound::akitas, 6}},
		aunt{data{compound::samoyeds, 5}, {compound::cars, 5}, {compound::children, 4}},
		aunt{data{compound::vizslas, 10}, {compound::cars, 4}, {compound::goldfish, 4}},
		aunt{data{compound::goldfish, 3}, {compound::samoyeds, 7}, {compound::akitas, 2}},
		aunt{data{compound::cats, 8}, {compound::children, 2}, {compound::vizslas, 7}},
		aunt{data{compound::cars, 9}, {compound::perfumes, 4}, {compound::trees, 9}},
		aunt{data{compound::trees, 8}, {compound::vizslas, 2}, {compound::goldfish, 5}},
		aunt{data{compound::cars, 6}, {compound::trees, 3}, {compound::vizslas, 3}},
		aunt{data{compound::cats, 6}, {compound::children, 7}, {compound::cars, 4}},
		aunt{data{compound::cats, 10}, {compound::perfumes, 2}, {compound::goldfish, 7}},
		aunt{data{compound::akitas, 8}, {compound::cats, 10}, {compound::perfumes, 8}},
		aunt{data{compound::vizslas, 8}, {compound::akitas, 5}, {compound::perfumes, 10}},
		aunt{data{compound::goldfish, 2}, {compound::vizslas, 5}, {compound::akitas, 7}},
		aunt{data{compound::akitas, 3}, {compound::perfumes, 0}, {compound::trees, 10}},
		aunt{data{compound::cats, 4}, {compound::vizslas, 5}, {compound::pomeranians, 6}},
		aunt{data{compound::children, 3}, {compound::vizslas, 7}, {compound::perfumes, 2}},
		aunt{data{compound::cars, 0}, {compound::pomeranians, 10}, {compound::perfumes, 0}},
		aunt{data{compound::akitas, 0}, {compound::goldfish, 9}, {compound::cars, 6}},
		aunt{data{compound::perfumes, 7}, {compound::cars, 4}, {compound::samoyeds, 5}},
		aunt{data{compound::akitas, 9}, {compound::trees, 10}, {compound::cars, 4}},
		aunt{data{compound::samoyeds, 10}, {compound::children, 6}, {compound::akitas, 7}},
		aunt{data{compound::trees, 8}, {compound::goldfish, 8}, {compound::perfumes, 8}},
		aunt{data{compound::goldfish, 3}, {compound::akitas, 2}, {compound::perfumes, 6}},
		aunt{data{compound::cats, 7}, {compound::trees, 0}, {compound::vizslas, 1}},
		aunt{data{compound::perfumes, 7}, {compound::cars, 7}, {compound::akitas, 7}},
		aunt{data{compound::goldfish, 0}, {compound::vizslas, 0}, {compound::samoyeds, 2}},
		aunt{data{compound::vizslas, 2}, {compound::children, 2}, {compound::cats, 3}},
		aunt{data{compound::vizslas, 2}, {compound::pomeranians, 9}, {compound::samoyeds, 3}},
		aunt{data{compound::cats, 1}, {compound::akitas, 3}, {compound::vizslas, 1}},
		aunt{data{compound::pomeranians, 10}, {compound::trees, 2}, {compound::goldfish, 7}},
		aunt{data{compound::samoyeds, 5}, {compound::trees, 7}, {compound::perfumes, 4}},
		aunt{data{compound::perfumes, 10}, {compound::cars, 1}, {compound::pomeranians, 3}},
		aunt{data{compound::trees, 6}, {compound::goldfish, 1}, {compound::cars, 0}},
		aunt{data{compound::cars, 6}, {compound::samoyeds, 4}, {compound::pomeranians, 5}},
		aunt{data{compound::goldfish, 3}, {compound::vizslas, 3}, {compound::akitas, 3}},
		aunt{data{compound::children, 5}, {compound::cats, 0}, {compound::cars, 4}},
		aunt{data{compound::goldfish, 3}, {compound::perfumes, 8}, {compound::pomeranians, 7}},
		aunt{data{compound::samoyeds, 6}, {compound::cars, 7}, {compound::perfumes, 10}},
		aunt{data{compound::trees, 4}, {compound::cars, 2}, {compound::vizslas, 7}},
		aunt{data{compound::samoyeds, 10}, {compound::perfumes, 9}, {compound::goldfish, 6}},
		aunt{data{compound::cars, 4}, {compound::trees, 2}, {compound::perfumes, 7}},
		aunt{data{compound::akitas, 3}, {compound::perfumes, 9}, {compound::cars, 9}},
		aunt{data{compound::akitas, 8}, {compound::vizslas, 2}, {compound::cats, 6}},
		aunt{data{compound::trees, 5}, {compound::goldfish, 7}, {compound::akitas, 3}},
		aunt{data{compound::perfumes, 9}, {compound::cars, 8}, {compound::vizslas, 2}},
		aunt{data{compound::trees, 3}, {compound::vizslas, 0}, {compound::children, 0}},
		aunt{data{compound::cars, 7}, {compound::trees, 2}, {compound::cats, 5}},
		aunt{data{compound::vizslas, 4}, {compound::cars, 10}, {compound::cats, 3}},
		aunt{data{compound::akitas, 10}, {compound::cats, 3}, {compound::samoyeds, 9}},
		aunt{data{compound::trees, 7}, {compound::children, 5}, {compound::goldfish, 6}},
		aunt{data{compound::cars, 2}, {compound::perfumes, 5}, {compound::cats, 7}},
		aunt{data{compound::samoyeds, 5}, {compound::trees, 10}, {compound::goldfish, 6}},
		aunt{data{compound::goldfish, 10}, {compound::perfumes, 4}, {compound::trees, 7}},
		aunt{data{compound::vizslas, 9}, {compound::trees, 9}, {compound::perfumes, 0}},
		aunt{data{compound::trees, 4}, {compound::goldfish, 9}, {compound::vizslas, 8}},
		aunt{data{compound::vizslas, 3}, {compound::cars, 3}, {compound::trees, 2}},
		aunt{data{compound::goldfish, 2}, {compound::akitas, 2}, {compound::trees, 2}},
		aunt{data{compound::children, 1}, {compound::cars, 0}, {compound::vizslas, 5}},
		aunt{data{compound::trees, 5}, {compound::akitas, 4}, {compound::goldfish, 6}},
		aunt{data{compound::akitas, 3}, {compound::vizslas, 7}, {compound::pomeranians, 5}},
		aunt{data{compound::goldfish, 10}, {compound::vizslas, 3}, {compound::trees, 1}},
		aunt{data{compound::cars, 2}, {compound::trees, 1}, {compound::akitas, 0}},
		aunt{data{compound::akitas, 10}, {compound::vizslas, 6}, {compound::samoyeds, 2}},
		aunt{data{compound::children, 5}, {compound::trees, 1}, {compound::samoyeds, 9}},
		aunt{data{compound::perfumes, 9}, {compound::trees, 6}, {compound::vizslas, 1}},
		aunt{data{compound::akitas, 7}, {compound::pomeranians, 6}, {compound::vizslas, 6}},
		aunt{data{compound::cats, 7}, {compound::children, 6}, {compound::vizslas, 7}},
		aunt{data{compound::trees, 2}, {compound::vizslas, 7}, {compound::samoyeds, 4}},
		aunt{data{compound::goldfish, 0}, {compound::samoyeds, 10}, {compound::cars, 4}},
		aunt{data{compound::pomeranians, 9}, {compound::children, 3}, {compound::vizslas, 5}},
		aunt{data{compound::akitas, 8}, {compound::vizslas, 4}, {compound::cars, 5}},
		aunt{data{compound::akitas, 0}, {compound::perfumes, 2}, {compound::pomeranians, 10}},
		aunt{data{compound::akitas, 9}, {compound::cars, 0}, {compound::trees, 2}},
		aunt{data{compound::vizslas, 10}, {compound::goldfish, 8}, {compound::akitas, 6}},
		aunt{data{compound::trees, 0}, {compound::cats, 6}, {compound::perfumes, 2}},
		aunt{data{compound::vizslas, 10}, {compound::cars, 1}, {compound::trees, 4}},
		aunt{data{compound::goldfish, 8}, {compound::perfumes, 6}, {compound::cats, 3}},
		aunt{data{compound::goldfish, 0}, {compound::children, 1}, {compound::akitas, 2}},
		aunt{data{compound::pomeranians, 10}, {compound::trees, 6}, {compound::samoyeds, 6}},
		aunt{data{compound::vizslas, 5}, {compound::akitas, 4}, {compound::pomeranians, 2}},
		aunt{data{compound::goldfish, 7}, {compound::trees, 0}, {compound::akitas, 5}},
		aunt{data{compound::goldfish, 4}, {compound::vizslas, 5}, {compound::cars, 7}},
		aunt{data{compound::perfumes, 7}, {compound::cats, 10}, {compound::cars, 4}},
		aunt{data{compound::samoyeds, 10}, {compound::cars, 9}, {compound::trees, 7}},
		aunt{data{compound::pomeranians, 8}, {compound::vizslas, 6}, {compound::cars, 3}},
		aunt{data{compound::cars, 4}, {compound::cats, 9}, {compound::akitas, 4}},
		aunt{data{compound::cars, 6}, {compound::trees, 2}, {compound::perfumes, 6}},
		aunt{data{compound::goldfish, 1}, {compound::cats, 2}, {compound::perfumes, 4}},
		aunt{data{compound::akitas, 6}, {compound::cats, 5}, {compound::cars, 8}},
		aunt{data{compound::cats, 4}, {compound::vizslas, 9}, {compound::akitas, 0}},
		aunt{data{compound::children, 8}, {compound::samoyeds, 9}, {compound::trees, 4}},
		aunt{data{compound::vizslas, 2}, {compound::samoyeds, 10}, {compound::perfumes, 7}},
		aunt{data{compound::goldfish, 7}, {compound::pomeranians, 4}, {compound::akitas, 10}},
		aunt{data{compound::perfumes, 8}, {compound::cats, 4}, {compound::akitas, 10}},
		aunt{data{compound::trees, 0}, {compound::cars, 9}, {compound::goldfish, 3}},
		aunt{data{compound::trees, 5}, {compound::samoyeds, 7}, {compound::perfumes, 8}},
		aunt{data{compound::cars, 4}, {compound::perfumes, 2}, {compound::goldfish, 0}},
		aunt{data{compound::vizslas, 4}, {compound::pomeranians, 7}, {compound::akitas, 1}},
		aunt{data{compound::akitas, 4}, {compound::goldfish, 3}, {compound::perfumes, 0}},
		aunt{data{compound::samoyeds, 3}, {compound::akitas, 10}, {compound::vizslas, 0}},
		aunt{data{compound::goldfish, 1}, {compound::akitas, 7}, {compound::vizslas, 6}},
		aunt{data{compound::perfumes, 1}, {compound::goldfish, 1}, {compound::pomeranians, 8}},
		aunt{data{compound::children, 5}, {compound::cars, 4}, {compound::cats, 4}},
		aunt{data{compound::vizslas, 5}, {compound::cars, 10}, {compound::cats, 3}},
		aunt{data{compound::trees, 2}, {compound::goldfish, 3}, {compound::cars, 1}},
		aunt{data{compound::trees, 10}, {compound::goldfish, 6}, {compound::perfumes, 2}},
		aunt{data{compound::akitas, 5}, {compound::trees, 6}, {compound::cats, 3}},
		aunt{data{compound::cars, 10}, {compound::children, 8}, {compound::goldfish, 0}},
		aunt{data{compound::cats, 2}, {compound::akitas, 0}, {compound::pomeranians, 4}},
		aunt{data{compound::perfumes, 1}, {compound::vizslas, 3}, {compound::cars, 3}},
		aunt{data{compound::samoyeds, 8}, {compound::cats, 5}, {compound::perfumes, 8}},
		aunt{data{compound::cars, 5}, {compound::akitas, 10}, {compound::trees, 2}},
		aunt{data{compound::vizslas, 9}, {compound::akitas, 9}, {compound::cars, 3}},
		aunt{data{compound::cars, 3}, {compound::perfumes, 1}, {compound::pomeranians, 9}},
		aunt{data{compound::akitas, 1}, {compound::cars, 4}, {compound::perfumes, 0}},
		aunt{data{compound::perfumes, 8}, {compound::vizslas, 2}, {compound::trees, 6}},
		aunt{data{compound::pomeranians, 5}, {compound::akitas, 9}, {compound::cats, 8}},
		aunt{data{compound::pomeranians, 8}, {compound::vizslas, 3}, {compound::goldfish, 10}},
		aunt{data{compound::trees, 2}, {compound::pomeranians, 0}, {compound::goldfish, 6}},
		aunt{data{compound::cats, 5}, {compound::akitas, 7}, {compound::goldfish, 6}},
		aunt{data{compound::goldfish, 6}, {compound::children, 4}, {compound::trees, 10}},
		aunt{data{compound::children, 1}, {compound::trees, 3}, {compound::akitas, 7}},
		aunt{data{compound::trees, 2}, {compound::samoyeds, 10}, {compound::goldfish, 3}},
		aunt{data{compound::samoyeds, 10}, {compound::cats, 0}, {compound::goldfish, 0}},
		aunt{data{compound::perfumes, 3}, {compound::children, 6}, {compound::pomeranians, 1}},
		aunt{data{compound::cars, 10}, {compound::pomeranians, 1}, {compound::samoyeds, 5}},
		aunt{data{compound::samoyeds, 9}, {compound::pomeranians, 7}, {compound::perfumes, 6}},
		aunt{data{compound::goldfish, 6}, {compound::trees, 8}, {compound::perfumes, 9}},
		aunt{data{compound::samoyeds, 10}, {compound::pomeranians, 9}, {compound::children, 10}},
		aunt{data{compound::perfumes, 3}, {compound::goldfish, 7}, {compound::cars, 9}},
		aunt{data{compound::cats, 3}, {compound::children, 4}, {compound::samoyeds, 8}},
		aunt{data{compound::trees, 0}, {compound::cars, 10}, {compound::vizslas, 10}},
		aunt{data{compound::pomeranians, 10}, {compound::children, 8}, {compound::perfumes, 2}},
		aunt{data{compound::cars, 5}, {compound::vizslas, 0}, {compound::samoyeds, 3}},
		aunt{data{compound::trees, 1}, {compound::goldfish, 8}, {compound::cars, 8}},
		aunt{data{compound::vizslas, 0}, {compound::cars, 2}, {compound::perfumes, 5}},
		aunt{data{compound::trees, 2}, {compound::cars, 3}, {compound::vizslas, 8}},
		aunt{data{compound::trees, 10}, {compound::children, 9}, {compound::cats, 1}},
		aunt{data{compound::pomeranians, 3}, {compound::perfumes, 1}, {compound::vizslas, 0}},
		aunt{data{compound::vizslas, 0}, {compound::perfumes, 6}, {compound::trees, 0}},
		aunt{data{compound::vizslas, 7}, {compound::pomeranians, 1}, {compound::akitas, 10}},
		aunt{data{compound::vizslas, 8}, {compound::trees, 2}, {compound::cars, 10}},
		aunt{data{compound::perfumes, 9}, {compound::cats, 5}, {compound::goldfish, 5}},
		aunt{data{compound::cats, 0}, {compound::akitas, 10}, {compound::perfumes, 9}},
		aunt{data{compound::cars, 4}, {compound::akitas, 1}, {compound::trees, 1}},
		aunt{data{compound::cars, 4}, {compound::perfumes, 5}, {compound::trees, 3}},
		aunt{data{compound::goldfish, 3}, {compound::akitas, 5}, {compound::samoyeds, 9}},
		aunt{data{compound::goldfish, 7}, {compound::perfumes, 5}, {compound::trees, 5}},
		aunt{data{compound::akitas, 4}, {compound::cats, 6}, {compound::cars, 8}},
		aunt{data{compound::children, 6}, {compound::goldfish, 10}, {compound::akitas, 7}},
		aunt{data{compound::akitas, 7}, {compound::vizslas, 5}, {compound::perfumes, 10}},
		aunt{data{compound::children, 7}, {compound::vizslas, 10}, {compound::akitas, 10}},
		aunt{data{compound::goldfish, 6}, {compound::akitas, 7}, {compound::trees, 2}},
		aunt{data{compound::vizslas, 6}, {compound::trees, 1}, {compound::akitas, 2}},
		aunt{data{compound::cars, 5}, {compound::vizslas, 3}, {compound::akitas, 7}},
		aunt{data{compound::vizslas, 4}, {compound::cats, 8}, {compound::perfumes, 7}},
		aunt{data{compound::akitas, 3}, {compound::trees, 0}, {compound::children, 2}},
		aunt{data{compound::cats, 7}, {compound::cars, 3}, {compound::children, 9}},
		aunt{data{compound::trees, 10}, {compound::vizslas, 3}, {compound::goldfish, 7}},
		aunt{data{compound::perfumes, 0}, {compound::goldfish, 7}, {compound::akitas, 4}},
		aunt{data{compound::cats, 6}, {compound::cars, 7}, {compound::vizslas, 0}},
		aunt{data{compound::vizslas, 4}, {compound::perfumes, 6}, {compound::goldfish, 5}},
		aunt{data{compound::pomeranians, 8}, {compound::trees, 1}, {compound::akitas, 9}},
		aunt{data{compound::goldfish, 7}, {compound::pomeranians, 6}, {compound::samoyeds, 9}},
		aunt{data{compound::perfumes, 10}, {compound::cars, 1}, {compound::trees, 8}},
		aunt{data{compound::trees, 0}, {compound::goldfish, 9}, {compound::children, 6}},
		aunt{data{compound::trees, 1}, {compound::cars, 6}, {compound::pomeranians, 8}},
		aunt{data{compound::perfumes, 9}, {compound::cars, 0}, {compound::vizslas, 10}},
		aunt{data{compound::samoyeds, 4}, {compound::akitas, 1}, {compound::vizslas, 9}},
		aunt{data{compound::perfumes, 0}, {compound::trees, 2}, {compound::cars, 4}},
		aunt{data{compound::akitas, 0}, {compound::perfumes, 5}, {compound::samoyeds, 4}},
		aunt{data{compound::akitas, 8}, {compound::vizslas, 6}, {compound::children, 2}},
		aunt{data{compound::children, 1}, {compound::trees, 8}, {compound::goldfish, 10}},
		aunt{data{compound::pomeranians, 4}, {compound::trees, 10}, {compound::cars, 9}},
		aunt{data{compound::perfumes, 5}, {compound::vizslas, 5}, {compound::akitas, 4}},
		aunt{data{compound::trees, 1}, {compound::akitas, 10}, {compound::vizslas, 6}},
		aunt{data{compound::samoyeds, 0}, {compound::goldfish, 9}, {compound::perfumes, 7}},
		aunt{data{compound::goldfish, 7}, {compound::samoyeds, 10}, {compound::trees, 1}},
		aunt{data{compound::samoyeds, 0}, {compound::pomeranians, 10}, {compound::vizslas, 6}},
		aunt{data{compound::children, 2}, {compound::cars, 10}, {compound::samoyeds, 2}},
		aunt{data{compound::trees, 2}, {compound::goldfish, 8}, {compound::cars, 0}},
		aunt{data{compound::samoyeds, 4}, {compound::goldfish, 9}, {compound::trees, 2}},
		aunt{data{compound::trees, 8}, {compound::akitas, 10}, {compound::perfumes, 3}},
		aunt{data{compound::samoyeds, 9}, {compound::goldfish, 2}, {compound::cars, 1}},
		aunt{data{compound::akitas, 2}, {compound::perfumes, 8}, {compound::trees, 2}},
		aunt{data{compound::children, 3}, {compound::goldfish, 6}, {compound::perfumes, 5}},
		aunt{data{compound::akitas, 8}, {compound::perfumes, 2}, {compound::samoyeds, 6}},
		aunt{data{compound::vizslas, 10}, {compound::akitas, 4}, {compound::pomeranians, 3}},
		aunt{data{compound::cats, 8}, {compound::perfumes, 3}, {compound::trees, 4}},
		aunt{data{compound::cars, 2}, {compound::children, 4}, {compound::pomeranians, 8}},
		aunt{data{compound::pomeranians, 4}, {compound::samoyeds, 2}, {compound::goldfish, 4}},
		aunt{data{compound::perfumes, 6}, {compound::cars, 4}, {compound::goldfish, 4}},
		aunt{data{compound::akitas, 0}, {compound::goldfish, 7}, {compound::perfumes, 5}},
		aunt{data{compound::perfumes, 4}, {compound::cars, 3}, {compound::akitas, 5}},
		aunt{data{compound::trees, 0}, {compound::vizslas, 0}, {compound::goldfish, 1}},
		aunt{data{compound::perfumes, 4}, {compound::vizslas, 2}, {compound::cars, 7}},
		aunt{data{compound::goldfish, 7}, {compound::pomeranians, 8}, {compound::trees, 0}},
		aunt{data{compound::goldfish, 7}, {compound::children, 9}, {compound::trees, 3}},
		aunt{data{compound::akitas, 1}, {compound::vizslas, 10}, {compound::trees, 2}},
		aunt{data{compound::perfumes, 2}, {compound::cars, 4}, {compound::goldfish, 10}},
		aunt{data{compound::pomeranians, 6}, {compound::vizslas, 9}, {compound::trees, 1}},
		aunt{data{compound::cars, 9}, {compound::trees, 0}, {compound::goldfish, 0}},
		aunt{data{compound::trees, 1}, {compound::goldfish, 1}, {compound::vizslas, 8}},
		aunt{data{compound::goldfish, 7}, {compound::samoyeds, 8}, {compound::children, 2}},
		aunt{data{compound::children, 1}, {compound::cats, 7}, {compound::vizslas, 8}},
		aunt{data{compound::cats, 2}, {compound::pomeranians, 6}, {compound::goldfish, 4}},
		aunt{data{compound::perfumes, 7}, {compound::cats, 3}, {compound::vizslas, 6}},
		aunt{data{compound::akitas, 4}, {compound::samoyeds, 5}, {compound::cars, 2}},
		aunt{data{compound::akitas, 3}, {compound::perfumes, 3}, {compound::cats, 9}},
		aunt{data{compound::perfumes, 10}, {compound::akitas, 6}, {compound::trees, 0}},
		aunt{data{compound::cars, 5}, {compound::children, 9}, {compound::perfumes, 8}},
		aunt{data{compound::vizslas, 10}, {compound::cars, 3}, {compound::perfumes, 5}},
		aunt{data{compound::children, 9}, {compound::perfumes, 1}, {compound::cars, 10}},
		aunt{data{compound::akitas, 0}, {compound::goldfish, 8}, {compound::trees, 3}},
		aunt{data{compound::cars, 7}, {compound::akitas, 8}, {compound::children, 3}},
		aunt{data{compound::cars, 4}, {compound::akitas, 9}, {compound::cats, 0}},
		aunt{data{compound::perfumes, 4}, {compound::samoyeds, 5}, {compound::goldfish, 6}},
		aunt{data{compound::perfumes, 10}, {compound::akitas, 1}, {compound::cars, 7}},
		aunt{data{compound::trees, 1}, {compound::goldfish, 3}, {compound::vizslas, 6}},
		aunt{data{compound::goldfish, 8}, {compound::pomeranians, 6}, {compound::trees, 10}},
		aunt{data{compound::akitas, 5}, {compound::vizslas, 8}, {compound::goldfish, 10}},
		aunt{data{compound::cats, 5}, {compound::trees, 4}, {compound::samoyeds, 0}},
		aunt{data{compound::perfumes, 8}, {compound::cars, 0}, {compound::cats, 3}},
		aunt{data{compound::akitas, 1}, {compound::trees, 10}, {compound::vizslas, 2}},
		aunt{data{compound::vizslas, 6}, {compound::akitas, 3}, {compound::children, 10}},
		aunt{data{compound::perfumes, 7}, {compound::trees, 9}, {compound::goldfish, 8}},
		aunt{data{compound::children, 6}, {compound::vizslas, 4}, {compound::perfumes, 5}},
		aunt{data{compound::vizslas, 6}, {compound::akitas, 8}, {compound::perfumes, 9}},
		aunt{data{compound::goldfish, 8}, {compound::cars, 4}, {compound::trees, 10}},
		aunt{data{compound::pomeranians, 8}, {compound::cars, 5}, {compound::vizslas, 0}},
		aunt{data{compound::cats, 10}, {compound::goldfish, 7}, {compound::akitas, 1}},
		aunt{data{compound::cats, 2}, {compound::children, 1}, {compound::cars, 6}},
		aunt{data{compound::perfumes, 3}, {compound::samoyeds, 6}, {compound::cars, 0}},
		aunt{data{compound::samoyeds, 10}, {compound::pomeranians, 6}, {compound::trees, 2}},
		aunt{data{compound::children, 2}, {compound::perfumes, 2}, {compound::pomeranians, 4}},
		aunt{data{compound::cats, 1}, {compound::perfumes, 5}, {compound::vizslas, 9}},
		aunt{data{compound::vizslas, 5}, {compound::perfumes, 2}, {compound::akitas, 7}},
		aunt{data{compound::samoyeds, 8}, {compound::goldfish, 6}, {compound::cats, 1}},
		aunt{data{compound::goldfish, 10}, {compound::perfumes, 9}, {compound::cars, 4}},
		aunt{data{compound::samoyeds, 0}, {compound::cars, 4}, {compound::vizslas, 4}},
		aunt{data{compound::trees, 2}, {compound::cars, 7}, {compound::akitas, 8}},
		aunt{data{compound::vizslas, 3}, {compound::perfumes, 5}, {compound::goldfish, 1}},
		aunt{data{compound::cats, 7}, {compound::cars, 4}, {compound::trees, 1}},
		aunt{data{compound::vizslas, 8}, {compound::akitas, 3}, {compound::goldfish, 0}},
		aunt{data{compound::cars, 6}, {compound::cats, 3}, {compound::perfumes, 2}},
		aunt{data{compound::goldfish, 1}, {compound::children, 9}, {compound::vizslas, 3}},
		aunt{data{compound::pomeranians, 5}, {compound::vizslas, 1}, {compound::cars, 10}},
		aunt{data{compound::children, 5}, {compound::perfumes, 5}, {compound::cats, 1}},
		aunt{data{compound::perfumes, 2}, {compound::goldfish, 7}, {compound::trees, 6}},
		aunt{data{compound::akitas, 2}, {compound::goldfish, 4}, {compound::perfumes, 10}},
		aunt{data{compound::samoyeds, 3}, {compound::goldfish, 0}, {compound::akitas, 1}},
		aunt{data{compound::trees, 8}, {compound::vizslas, 9}, {compound::goldfish, 0}},
		aunt{data{compound::goldfish, 8}, {compound::samoyeds, 0}, {compound::trees, 0}},
		aunt{data{compound::perfumes, 7}, {compound::cars, 5}, {compound::trees, 0}},
		aunt{data{compound::vizslas, 3}, {compound::pomeranians, 2}, {compound::perfumes, 5}},
		aunt{data{compound::cars, 5}, {compound::perfumes, 5}, {compound::akitas, 5}},
		aunt{data{compound::children, 8}, {compound::trees, 1}, {compound::pomeranians, 4}},
		aunt{data{compound::pomeranians, 0}, {compound::akitas, 1}, {compound::vizslas, 8}},
		aunt{data{compound::akitas, 10}, {compound::perfumes, 10}, {compound::samoyeds, 8}},
		aunt{data{compound::perfumes, 6}, {compound::vizslas, 4}, {compound::cats, 6}},
		aunt{data{compound::children, 6}, {compound::pomeranians, 5}, {compound::samoyeds, 4}},
		aunt{data{compound::vizslas, 1}, {compound::trees, 5}, {compound::akitas, 1}},
		aunt{data{compound::vizslas, 10}, {compound::perfumes, 10}, {compound::pomeranians, 3}},
		aunt{data{compound::samoyeds, 3}, {compound::trees, 2}, {compound::cars, 5}},
		aunt{data{compound::cats, 6}, {compound::children, 3}, {compound::perfumes, 0}},
		aunt{data{compound::pomeranians, 10}, {compound::cats, 3}, {compound::vizslas, 5}},
	};

	std::array<int, 10> const sue{
		3, //compound::pomeranians
		5, //compound::goldfish
		3, //compound::children
		2, //compound::samoyeds
		0, //compound::akitas
		0, //compound::vizslas
		2, //compound::cars
		1, //compound::perfumes
		7, //compound::cats
		3, //compound::trees
	};

	auto const it = std::find_if(aunts.begin(), aunts.end(), [&sue](aunt const& a) {
		auto const match_data = [&sue](data const& d) {
			int const index = static_cast<int>(d.first);
			if (d.first <= compound::goldfish)
				return d.second < sue[index];
			else if (d.first >= compound::cats)
				return d.second > sue[index];
			else
				return d.second == sue[index];
		};

		return
			match_data(a[0]) &&
			match_data(a[1]) &&
			match_data(a[2]);
	});

	if (it != aunts.end())
		std::cout << 1 + std::distance(aunts.begin(), it) << '\n';
}
