#pragma once
#include <utility>
#include <array>
#include <map>

enum class guest { Alice, Bob, Carol, David, Eric, Frank, George, Mallory, Myself };

using guest_pair = std::pair<guest, guest>;
std::map<guest_pair, int> happiness{
	{ {guest::Alice, guest::Bob}, 2},
	{ {guest::Alice, guest::Carol}, 26},
	{ {guest::Alice, guest::David}, -82},
	{ {guest::Alice, guest::Eric}, -75},
	{ {guest::Alice, guest::Frank}, 42},
	{ {guest::Alice, guest::George}, 38},
	{ {guest::Alice, guest::Mallory}, 39},
	{ {guest::Alice, guest::Myself}, 0},
	{ {guest::Bob, guest::Alice}, 40},
	{ {guest::Bob, guest::Carol}, -61},
	{ {guest::Bob, guest::David}, -15},
	{ {guest::Bob, guest::Eric}, 63},
	{ {guest::Bob, guest::Frank}, 41},
	{ {guest::Bob, guest::George}, 30},
	{ {guest::Bob, guest::Mallory}, 87},
	{ {guest::Bob, guest::Myself}, 0},
	{ {guest::Carol, guest::Alice}, -35},
	{ {guest::Carol, guest::Bob}, -99},
	{ {guest::Carol, guest::David}, -51},
	{ {guest::Carol, guest::Eric}, 95},
	{ {guest::Carol, guest::Frank}, 90},
	{ {guest::Carol, guest::George}, -16},
	{ {guest::Carol, guest::Mallory}, 94},
	{ {guest::Carol, guest::Myself}, 0},
	{ {guest::David, guest::Alice}, 36},
	{ {guest::David, guest::Bob}, -18},
	{ {guest::David, guest::Carol}, -65},
	{ {guest::David, guest::Eric}, -18},
	{ {guest::David, guest::Frank}, -22},
	{ {guest::David, guest::George}, 2},
	{ {guest::David, guest::Mallory}, 42},
	{ {guest::David, guest::Myself}, 0},
	{ {guest::Eric, guest::Alice}, -65},
	{ {guest::Eric, guest::Bob}, 24},
	{ {guest::Eric, guest::Carol}, 100},
	{ {guest::Eric, guest::David}, 51},
	{ {guest::Eric, guest::Frank}, 21},
	{ {guest::Eric, guest::George}, 55},
	{ {guest::Eric, guest::Mallory}, -44},
	{ {guest::Eric, guest::Myself}, 0},
	{ {guest::Frank, guest::Alice}, -48},
	{ {guest::Frank, guest::Bob}, 91},
	{ {guest::Frank, guest::Carol}, 8},
	{ {guest::Frank, guest::David}, -66},
	{ {guest::Frank, guest::Eric}, 97},
	{ {guest::Frank, guest::George}, -9},
	{ {guest::Frank, guest::Mallory}, -92},
	{ {guest::Frank, guest::Myself}, 0},
	{ {guest::George, guest::Alice}, -44},
	{ {guest::George, guest::Bob}, -25},
	{ {guest::George, guest::Carol}, 17},
	{ {guest::George, guest::David}, 92},
	{ {guest::George, guest::Eric}, -92},
	{ {guest::George, guest::Frank}, 18},
	{ {guest::George, guest::Mallory}, 97},
	{ {guest::George, guest::Myself}, 0},
	{ {guest::Mallory, guest::Alice}, 92},
	{ {guest::Mallory, guest::Bob}, -96},
	{ {guest::Mallory, guest::Carol}, -51},
	{ {guest::Mallory, guest::David}, -81},
	{ {guest::Mallory, guest::Eric}, 31},
	{ {guest::Mallory, guest::Frank}, -73},
	{ {guest::Mallory, guest::George}, -89},
	{ {guest::Mallory, guest::Myself}, 0},
	{ {guest::Myself, guest::Alice}, 0},
	{ {guest::Myself, guest::Bob}, 0},
	{ {guest::Myself, guest::Carol}, 0},
	{ {guest::Myself, guest::David}, 0},
	{ {guest::Myself, guest::Eric}, 0},
	{ {guest::Myself, guest::Frank}, 0},
	{ {guest::Myself, guest::George}, 0},
	{ {guest::Myself, guest::Mallory}, 0},
};